DROP TABLE VYPIS CASCADE CONSTRAINTS;
DROP TABLE PRIKAZ CASCADE CONSTRAINTS;
DROP TABLE ZAMESTNANEC CASCADE CONSTRAINTS;
DROP TABLE UCET CASCADE CONSTRAINTS;
DROP TABLE SPRAVUJE CASCADE CONSTRAINTS;
DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE DISPONUJE CASCADE CONSTRAINTS;

CREATE TABLE UCET (
    cislo INTEGER NOT NULL, -- asi BIGINT, NUMBER
    datum_zalozenia DATE NOT NULL,
    zostatok DECIMAL(20,2) DEFAULT 0,
    IBAN VARCHAR(24), -- ERIKA TODO
    typ VARCHAR(255) NOT NULL, -- TODO
    urok DECIMAL(6,3),
    poplatok DECIMAL(10,3),
    ID_klient INTEGER NOT NULL,

    CONSTRAINT PK_cislo PRIMARY KEY (cislo),
    CONSTRAINT FK_ID_klient FOREIGN KEY (ID_klient) REFERENCES KLIENT
);

CREATE TABLE VYPIS (
    poradove_cislo INTEGER NOT NULL,
    datum_zalozenia DATE NOT NULL,
    cislo INTEGER NOT NULL,
    

    CONSTRAINT PK_poradove_cislo PRIMARY KEY (nazov, stupnica),
    CONSTRAINT FK_cislo FOREIGN KEY (cislo) REFERENCES UCET
);

CREATE TABLE VYPIS (
    poradove_cislo INTEGER NOT NULL,
    datum_zalozenia DATE NOT NULL,
    cislo INTEGER NOT NULL,
    

    CONSTRAINT PK_poradove_cislo PRIMARY KEY (nazov, stupnica),
    CONSTRAINT FK_cislo FOREIGN KEY (cislo) REFERENCES UCET
);